#!/usr/bin/env python3

import argparse
import sys

from filelock import Timeout, FileLock
from typing import List


def main(args: List[str]):
    """
    The main function
    
    Arguments:
        args {List[str]} -- input arguments for main
    """

    parser = argparse.ArgumentParser(description="pylock-based file lock redirector")
    parser.add_argument(
        "stdin", nargs="?", type=argparse.FileType("r"), default=sys.stdin
    )
    parser.add_argument(
        "--start", type=str, help="Chunk start line", default="Begin chunk"
    )
    parser.add_argument("--stop", type=str, help="Chunk stop line", default="End chunk")
    parser.add_argument("fout", type=str, help="Out file")
    args = parser.parse_args()

    buffer = []
    start = lambda s: args.start in s
    stop = lambda s: args.stop in s

    lock = FileLock(f"{args.fout}.lock")
    for line in args.stdin:
        if start(line):
            buffer = []
        elif stop(line):
            with lock.acquire():
                with open(f"{args.fout}", "a") as fout:
                    fout.writelines(buffer+[line])
            buffer = []
            continue
        buffer.append(line)

if __name__ == "__main__":
    main(sys.argv[1:])
