#!/bin/bash

#This is adapter for check_hkl and compare_hkl, whio
while [[ $# -gt 0 ]]; do
	key="$1"
	if [[ ${key} == "--fom" ]]; then
		fom="$2"
		case "$fom" in
		"RanoRsplit")
			ARGS="${ARGS} --fom Rano/Rsplit"
		;;
		*)
			ARGS="${ARGS} --fom ${fom}"
		esac
		shift
	else
		ARGS="${ARGS} ${key}"
	fi
	shift
done

echo $ARGS
		
